serviceAccount: ci-cd-cloud-run-invoker@fitnessist-capstone-project.iam.gserviceaccount.com

options:
    logging: CLOUD_LOGGING_ONLY

steps:
    # Langkah 1: Menginstal dependensi
    - name: "gcr.io/cloud-builders/npm"
      args: ["install"]

    - name: "gcr.io/cloud-builders/npm"
      args: ["run", "test:unit"]

      # Langkah 2: Mendapatkan nilai dari Secret Manager
    - name: "gcr.io/cloud-builders/gcloud"
      entrypoint: "bash"
      args:
      - "-c"
      - |
        SECRET_VALUE=$(gcloud secrets versions access latest --secret=fitnessist_db_password --format='value(payload.data)' | base64 -d)
        echo "$SECRET_VALUE" > database-password.txt

    - name: "gcr.io/cloud-builders/docker"
      args:
          - "build"
          - "--build-arg"
          - "APP_HOST=$_APP_HOST"
          - "--build-arg"
          - "APP_PORT=$_APP_PORT"
          - "--build-arg"
          - "DATABASE_NAME=$_DATABASE_NAME"
          - "--build-arg"
          - "DATABASE_HOST=$_DATABASE_HOST"
          - "--build-arg"
          - "DATABASE_USER=$_DATABASE_USER"
          - "-t"
          - "gcr.io/$PROJECT_ID/fitnessist-image"
          - "."

    - name: "gcr.io/cloud-builders/gcloud"
      args:
          - "run"
          - "deploy"
          - "fitnessist-staging"
          - "--image=gcr.io/$PROJECT_ID/fitnessist-image"
          - "--region=asia-southeast2"
          - "--platform=managed"
          - "--allow-unauthenticated"
          - "--memory=256Mi"
          - "--timeout=60s"
          - "--set-env-vars=APP_HOST=http://localhost,APP_PORT=$_APP_PORT,DATABASE_HOST=$_DATABASE_HOST,DATABASE_USER=$_DATABASE_USER,DATABASE_PORT=$_DATABASE_PORT,DATABASE_NAME=$_DATABASE_NAME"

images:
    - "gcr.io/$PROJECT_ID/fitnessist-image"
