serviceAccount: ci-cd-cloud-run-invoker@fitnessist-capstone-project.iam.gserviceaccount.com

options:
    logging: CLOUD_LOGGING_ONLY

steps:
    # Langkah 1: Menginstal dependensi
    - name: "gcr.io/cloud-builders/npm"
      args: ["install"]

    - name: "gcr.io/cloud-builders/npm"
      args: ["run", "test:unit"]

    - name: "gcr.io/cloud-builders/docker"
      secretEnv: ["DATABASE_PASSWORD"]
      args:
          - "build"
          - "--build-arg"
          - "APP_HOST=$_APP_HOST"
          - "--build-arg"
          - "APP_PORT=$_APP_PORT"
          - "--build-arg"
          - "DATABASE_NAME=$_DATABASE_NAME"
          - "--build-arg"
          - "DATABASE_HOST=$_DATABASE_HOST"
          - "--build-arg"
          - "DATABASE_USER=$_DATABASE_USER"
          - "--build-arg"
          - "DATABASE_PASSWORD=$$DATABASE_PASSWORD"
          - "-t"
          - "gcr.io/$PROJECT_ID/fitnessist-image"
          - "."

      # Langkah 4: Menerbitkan gambar ke Container Registry
    - name: "gcr.io/cloud-builders/docker"
      args:
          - "push"
          - "gcr.io/$PROJECT_ID/fitnessist-image"
      timeout: 600s

    - name: "gcr.io/cloud-builders/gcloud"
      secretEnv: ["DATABASE_PASSWORD"]
      args:
          - "run"
          - "deploy"
          - "fitnessist-staging"
          - "--image=gcr.io/$PROJECT_ID/fitnessist-image"
          - "--region=asia-southeast2"
          - "--platform=managed"
          - "--allow-unauthenticated"
          - "--memory=256Mi"
          - "--timeout=60s"
          - "--set-env-vars=APP_HOST=http://localhost,APP_PORT=$_APP_PORT,DATABASE_HOST=$_DATABASE_HOST,DATABASE_USER=$_DATABASE_USER,DATABASE_PASSWORD=$$DATABASE_PASSWORD,DATABASE_PORT=$_DATABASE_PORT,DATABASE_NAME=$_DATABASE_NAME"

availableSecrets:
    secretManager:
        - versionName: projects/$PROJECT_ID/secrets/fitnessist_db_password/versions/latest
          env: "DATABASE_PASSWORD"

images:
    - "gcr.io/$PROJECT_ID/fitnessist-image"
