steps:
    # Langkah 1: Menginstal dependensi
    - name: "gcr.io/cloud-builders/npm"
      args: ["install"]

    - name: "gcr.io/cloud-builders/npm"
      args: ["run", "test"]

      # Langkah 2: Mendapatkan nilai dari Secret Manager
    - name: "gcr.io/cloud-builders/gcloud"
      args:
          - "secrets"
          - "versions"
          - "access"
          - "latest"
          - "--secret=fitnessist_db_password"
          - '--format="get(payload.data)"'
          - ">>"
          - "database-password.txt"

    - name: "gcr.io/cloud-builders/docker"
      args:
          - "build"
          - "--build-arg"
          - "APP_HOST=$APP_HOST"
          - "--build-arg"
          - "APP_PORT=8000"
          - "--build-arg"
          - "DATABASE_NAME=$DATABASE_NAME"
          - "--build-arg"
          - "DATABASE_HOST=$DATABASE_HOST"
          - "--build-arg"
          - "DATABASE_USER=$DATABASE_USER"
          - "--build-arg"
          - "DATABASE_PASSWORD=$(cat database-password.txt)"
          - "-t"
          - "gcr.io/$GOOGLE_CLOUD_PROJECT/fitnessist-image"
          - "."

    - name: "gcr.io/cloud-builders/gcloud"
      args:
          - "run"
          - "deploy"
          - "fitnessist-staging"
          - "--image=gcr.io/$PROJECT_ID/fitnessist-image"
          - "--region=asia-southeast2"
          - "--platform=managed"
          - "--allow-unauthenticated"
          - "--memory=256Mi"
          - "--timeout=60s"
          - "--set-env-vars=APP_HOST=$$(_get_service_url),APP_PORT=$APP_PORT,DATABASE_HOST=$DATABASE_HOST,DATABASE_USER=$DATABASE_USER,DATABASE_PORT=$DATABASE_PORT,DATABASE_NAME=$DATABASE_NAME"

substitutions:
  _get_service_url: 'gcloud run services describe fitnessist-staging --region=asia-southeast2 --format=value(status.url)'

images:
    - "gcr.io/$PROJECT_ID/fitnessist-image"
