serviceAccount: ci-cd-cloud-run-invoker@fitnessist-capstone-project.iam.gserviceaccount.com

options:
    logging: CLOUD_LOGGING_ONLY

steps:
    # Langkah 1: Menginstal dependensi
    - name: "gcr.io/cloud-builders/npm"
      args: ["install"]

    - name: "gcr.io/cloud-builders/npm"
      args: ["run", "test"]

      # Langkah 2: Mendapatkan nilai dari Secret Manager
    - name: "gcr.io/cloud-builders/gcloud"
      args:
          - "secrets"
          - "versions"
          - "access"
          - "latest"
          - "--secret=fitnessist_db_password"
          - '--format="get(payload.data)"'
          - ">>"
          - "database-password.txt"

    - name: "gcr.io/cloud-builders/docker"
      env:
        - "APP_HOST=http://localhost"
        - "APP_PORT=8000"
      args:
          - "build"
          - "-t"
          - "gcr.io/$GOOGLE_CLOUD_PROJECT/fitnessist-image"
          - "."

    - name: "gcr.io/cloud-builders/gcloud"
      args:
          - "run"
          - "deploy"
          - "fitnessist-staging"
          - "--image=gcr.io/$PROJECT_ID/fitnessist-image"
          - "--region=asia-southeast2"
          - "--platform=managed"
          - "--allow-unauthenticated"
          - "--memory=256Mi"
          - "--timeout=60s"
          - "--set-env-vars=APP_HOST=http://localhost,APP_PORT=$APP_PORT,DATABASE_HOST=$DATABASE_HOST,DATABASE_USER=$DATABASE_USER,DATABASE_PORT=$DATABASE_PORT,DATABASE_NAME=$DATABASE_NAME"

images:
    - "gcr.io/$PROJECT_ID/fitnessist-image"
