steps:
    - name: "gcr.io/cloud-builders/docker"
      args:
          - "build"
          - "--build-arg"
          - "APP_HOST=$$APP_HOST"
          - "--build-arg"
          - "APP_PORT=8000"
          - "--build-arg"
          - "DATABASE_NAME=$$DATABASE_NAME"
          - "--build-arg"
          - "DATABASE_HOST=$$DATABASE_HOST"
          - "--build-arg"
          - "DATABASE_USER=$$DATABASE_USER"
          - "--build-arg"
          - "DATABASE_PASSWORD=$$DATABASE_PASSWORD"
          - "-t"
          - "gcr.io/$GOOGLE_CLOUD_PROJECT/fitnessist-api-stagging"
          - "."
images:
    - "gcr.io/$GOOGLE_CLOUD_PROJECT/fitnessist-api-stagging"
