version: "3.4"

services:
    cleanresttypescriptboilerplate:
        image: cleanresttypescriptboilerplate
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: development
        ports:
            - 8000:8000
            - 9229:9229
        depends_on: 
            - db
        command: ["node", "--inspect=0.0.0.0:9229", "dist/main/app.js"]

    db:
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}
