version: "3.4"

services:
    app:
        image: app
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                - APP_HOST=localhost
                - APP_PORT=8000
                - DATABASE_NAME=example_db
                - DATABASE_HOST=localhost
                - DATABASE_USER=postgres
                - DATABASE_PASSWORD=root
        environment:
            NODE_ENV: production
        ports:
            - 8000:8000
        env_file:
            - .env
        depends_on:
            - db

    db:
        image: postgres
        ports:
            - 5432:5432
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${DATABASE_USER:-postgres}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-root}
            - POSTGRES_DB=${DATABASE_NAME:-example_db}
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
