version: "3"
services:
    app:
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - 8000:8000
        depends_on:
            - db

    db:
        image: postgres:13
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORDJ}
            - POSTGRES_DB=${DATABASE_NAME}
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
